import { Container } from '@chakra-ui/react'
import Head from 'next/head'
import Footer from '../footer'
import NavBar from '../navbar'

type LayOutProps = {
    children: React.ReactNode 
}
const Main: React.FC<LayOutProps> = (props) => {
    return (
       <Container maxW={'900px'} mt={'20px'}>
            <Head>
                <title>Nishu Murmu</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <Container> 
                {props.children}
            </Container>
            <Footer />
        </Container>
    )
}

export default Main
